import React,{useEffect,useMemo,useState} from 'react';
import {Copy,ExternalLink,Lock,Save,Search,Store,CheckCircle2} from 'lucide-react';
import {SectionTitle} from '../components/common';

export default function Catalogo({products=[],userId,apiUrl,card,border,subtext,accent,text}:any){
 const [cfg,setCfg]=useState<any>({}); const [vipPassword,setVipPassword]=useState(''); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false); const [query,setQuery]=useState('');
 const base=(apiUrl||'http://localhost:3333').replace(/\/$/,'');
 const headers=()=>({ 'Content-Type':'application/json','Authorization':`Bearer ${localStorage.getItem('byse_token')||''}`});
 useEffect(()=>{(async()=>{try{const r=await fetch(`${base}/api/catalogo/config`,{headers:headers()});if(r.ok)setCfg(await r.json())}catch(e){console.error(e)}})()},[base]);
 const publicUrl=cfg.publicUrl||`${window.location.origin}/catalogo/${userId||''}`;
 const filtered=products.filter((p:any)=>String(p.name||'').toLowerCase().includes(query.toLowerCase()));
 const save=async()=>{setSaving(true);setSaved(false);try{const r=await fetch(`${base}/api/catalogo/config`,{method:'PUT',headers:headers(),body:JSON.stringify({...cfg,vipPassword})});if(!r.ok)throw new Error();const d=await r.json();setCfg({...cfg,publicUrl:d.publicUrl,vipConfigured:Boolean(vipPassword)||cfg.vipConfigured});setVipPassword('');setSaved(true)}catch(e){alert('Não foi possível salvar as configurações do catálogo.')}finally{setSaving(false)}};
 const copy=async()=>{await navigator.clipboard?.writeText(publicUrl);setSaved(true);setTimeout(()=>setSaved(false),2000)};
 return <div><SectionTitle title="Catálogo" sub="Publique o estoque disponível e ofereça preços VIP com senha por loja" subtext={subtext}/>
 <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:18}}>
  <div style={{background:card,border:`1px solid ${border}`,borderRadius:14,padding:18}}><div style={{display:'flex',alignItems:'center',gap:8,fontWeight:800}}><Store size={17} color={accent}/> Link público da loja</div><p style={{fontSize:12,color:subtext}}>Compartilhe este endereço. O cliente verá somente os produtos da sua loja.</p><div style={{display:'flex',gap:8}}><input readOnly value={publicUrl} style={{flex:1,padding:10,border:`1px solid ${border}`,borderRadius:8,background:'transparent',color:text}}/><button onClick={copy} style={{padding:'0 12px',border:0,borderRadius:8,background:accent,color:'#fff'}}><Copy size={15}/></button><button onClick={()=>window.open(publicUrl,'_blank')} style={{padding:'0 12px',border:`1px solid ${border}`,borderRadius:8,background:'transparent',color:text}}><ExternalLink size={15}/></button></div></div>
  <div style={{background:card,border:`1px solid ${border}`,borderRadius:14,padding:18}}><div style={{display:'flex',alignItems:'center',gap:8,fontWeight:800}}><Lock size={17} color={accent}/> Acesso VIP</div><p style={{fontSize:12,color:subtext}}>Defina uma senha. Ela será armazenada com hash no banco e validada no servidor.</p><input type="password" value={vipPassword} onChange={e=>setVipPassword(e.target.value)} placeholder={cfg.vipConfigured?'Senha já configurada — informe outra para trocar':'Defina a senha VIP'} style={{width:'100%',boxSizing:'border-box',padding:10,border:`1px solid ${border}`,borderRadius:8,background:'transparent',color:text,marginBottom:8}}/><button onClick={save} disabled={saving} style={{padding:'9px 14px',border:0,borderRadius:8,background:accent,color:'#fff',fontWeight:800}}><Save size={14} style={{verticalAlign:'middle',marginRight:5}}/>{saving?'Salvando...':'Salvar configuração'}</button>{saved&&<span style={{fontSize:11,color:'#22c55e',marginLeft:8}}><CheckCircle2 size={13} style={{verticalAlign:'middle'}}/> Salvo</span>}</div>
 </div>
 <div style={{background:card,border:`1px solid ${border}`,borderRadius:14,padding:18}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><h3 style={{margin:0}}>Produtos publicados</h3><div style={{display:'flex',alignItems:'center',gap:7,border:`1px solid ${border}`,borderRadius:8,padding:'7px 9px'}}><Search size={14} color={subtext}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar" style={{border:0,outline:0,background:'transparent',color:text}}/></div></div>{filtered.length===0?<p style={{color:subtext}}>Nenhum produto encontrado.</p>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(190px,1fr))',gap:10}}>{filtered.map((p:any)=><div key={p.id} style={{border:`1px solid ${border}`,borderRadius:10,padding:12}}><b>{p.name}</b><div style={{fontSize:12,color:subtext,marginTop:4}}>{p.category||'Sem categoria'}</div><div style={{marginTop:8,fontWeight:900}}>{Number(p.price||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div>{p.vip_price!=null&&<div style={{fontSize:11,color:'#22c55e'}}>VIP: {Number(p.vip_price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div>}</div>)}</div>}</div>
 </div>
}
