// @ts-nocheck
import React,{useEffect,useState} from 'react';
import {Lock,ShoppingBag,MessageCircle,CheckCircle2} from 'lucide-react';

export function PublicCatalog(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[password,setPassword]=useState(''),[vip,setVip]=useState(false),[showVip,setShowVip]=useState(false),[loading,setLoading]=useState(true);
 const base=(import.meta.env.VITE_API_URL||'http://localhost:3333').replace(/\/$/,'');
 const id=window.location.pathname.split('/')[2];
 useEffect(()=>{fetch(`${base}/api/public/catalogo/${id}`).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(setData).catch(()=>setError('Catálogo não encontrado.')).finally(()=>setLoading(false))},[id]);
 const verify=async()=>{const r=await fetch(`${base}/api/public/catalogo/${id}/vip/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok)return alert((await r.json()).error||'Senha inválida.');setVip(true);setShowVip(false);setPassword('');};
 if(loading)return <div style={{minHeight:'100vh',display:'grid',placeItems:'center'}}>Carregando catálogo...</div>;
 if(error)return <div style={{minHeight:'100vh',display:'grid',placeItems:'center'}}>{error}</div>;
 return <div style={{minHeight:'100vh',background:'#f6f7f9',padding:'24px 16px',fontFamily:'Arial,sans-serif',color:'#171717'}}><div style={{maxWidth:1000,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:24}}><div><h1 style={{margin:0}}>{data.storeName||'Catálogo'}</h1><p style={{color:'#666'}}>Produtos disponíveis em estoque</p></div>{data.vipEnabled&&<button onClick={()=>setShowVip(true)} style={{padding:'10px 14px',border:0,borderRadius:10,background:vip?'#16a34a':'#f59e0b',color:'#fff',fontWeight:800}}>{vip?<><CheckCircle2 size={14}/> VIP ativo</>:<><Lock size={14}/> Acessar VIP</>}</button>}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(210px,1fr))',gap:14}}>{(data.products||[]).map((p:any)=><div key={p.id} style={{background:'#fff',border:'1px solid #e5e7eb',borderRadius:14,overflow:'hidden'}}>{p.image_url&&<img src={p.image_url} style={{width:'100%',height:150,objectFit:'cover'}}/>}<div style={{padding:14}}><small style={{color:'#777'}}>{p.category||'Produto'}</small><h3>{p.name}</h3><div style={{fontWeight:900,fontSize:18}}>{Number(vip&&p.vip_price!=null?p.vip_price:p.price||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div>{vip&&p.vip_price!=null&&<small style={{color:'#16a34a'}}>Preço VIP</small>}<a href={`https://wa.me/${String(data.whatsapp||'').replace(/\D/g,'')}?text=${encodeURIComponent(`Olá! Tenho interesse em ${p.name}`)}`} target="_blank" rel="noreferrer" style={{display:'block',marginTop:12,textAlign:'center',padding:9,borderRadius:9,background:'#25D366',color:'#fff',textDecoration:'none',fontWeight:800}}><MessageCircle size={14}/> Comprar via WhatsApp</a></div></div>)}</div></div>{showVip&&<div style={{position:'fixed',inset:0,background:'#0008',display:'grid',placeItems:'center',padding:20}}><div style={{background:'#fff',padding:22,borderRadius:14,width:'100%',maxWidth:360}}><h3><Lock size={17}/> Acesso VIP</h3><p style={{color:'#666',fontSize:13}}>Digite a senha fornecida pela loja.</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&verify()} style={{width:'100%',boxSizing:'border-box',padding:11,border:'1px solid #ddd',borderRadius:9}}/><div style={{display:'flex',gap:8,marginTop:12}}><button onClick={()=>setShowVip(false)} style={{flex:1,padding:10,border:0,borderRadius:9}}>Cancelar</button><button onClick={verify} style={{flex:1,padding:10,border:0,borderRadius:9,background:'#f59e0b',color:'#fff',fontWeight:800}}>Desbloquear</button></div></div></div>}</div>;
}
